### ISSUE TITLE
Auto-clear on tab close + white list

### ISSUE THREAD

**Issue by danielnyga** [tmorin/ff-cpdn#3]
This is more a feature request than an issue. 
First of all, this is the first FF extension from the many that I've tried that _really_ removes the private data reliably. So, good job!

It would be great if one had an option to auto-clear the data of a specific site as soon as the tab closes, and a white list to specify trusted sites to exclude from auto-clearing. Just like the extension "Cookie AutoDelete" does with cookies: https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/?src=search

**Comment by tmorin** [comment]
Hi @danielnyga ,

Thank for the feedback.

The idea might be interesting. However, I do not want to change the current "flow", i.e. the single click on the button.

I will figure out how I could be able to, according a configuration, trigger the action or the display of a pop-up.

Best regards

**Comment by tmorin** [comment]
Hi @danielnyga,

In order to be able to properly clear data related to a domain once a tab is closed, a big effort of development has to be done. Right know I do not have the time to implement it.

I recommend you to follow (i.e. subscribe to the notifications) the issues  #4 and #5 in order to be notified automatically.

Best regards
